### ISSUE TITLE
Install with Docker Desktop for Windows

### ISSUE THREAD

**Issue by MajorOli** [Sebbo94BY/teamspeak-dynamic-banner#148] opened 2023-09-11 05:48 UTC
**Environment**
- TeamSpeak Dynamic Banner Version: latest
- Operating System: Windows 10 with Docker Desktop for Windows with wsl version 2

**Describe the bug**
After Docker pulling is finished i try to run `docker/scripts/prepare-docker-setup.sh` and its end with 
docker `bash /usr/bin/env: 'bash\r': No such file or directory`

**To Reproduce**
1. clone the repo to an Windows folder
2. Follow the `docs/CONTRIBUTE.md` instruction 
3. The Step `/tmp/prepare-docker-setup.sh` throw the error `bash /usr/bin/env: 'bash\r': No such file or directory`

**Additional context**
After i changed all files in the Docker folders from `CRLF` to `LF` the Script run without any errors and the install is successed
When you clone this repo to a Ubuntu Server directly there are no issues with CRLF and LF line seperators

Maybe, you can use `.gitattributes` to handel line endings:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by Sebbo94BY** [comment] 2023-09-18 20:50
Hey @MajorOli ,
I'm unfortunately unable to reproduce this issue.

All files in this repository already have the `LF` EoL. There is no single file with `CRLF` EoL as you can check with Git:
```shell
$ git ls-files --eol | grep -i crlf
$
```

Even forcing a conversion from `CRLF` to `LF` doesn't change anything:
```shell
find docker/ -type f | xargs dos2unix {}
```

Did your text editor maybe automatically convert those files to `CRLF` since you've checked it out on Windows?

However, I've now explicitly defined `eol=lf` in the Git attributes.

**Comment by Sebbo94BY** [comment] 2023-09-29 12:41
As discussed personally, I'll close this ticket now since it's not reproducible and the files in Git have already the required permissions / format.

**Closed by Sebbo94BY** 2023-09-29 12:41 UTC
Labels: bug
